import Head from "next/head";
import { useState } from "react";
const axios = require("axios");

export default function Home() {
  const [text, setText] = useState("");
  const [result, setResult] = useState("");

  async function getSentiment() {
    const res = await axios.post("/api/classify", {
      sentence: text,
    });
    setResult(res.data);
    console.log(res.data);
  }
  const handleGetSentiment = (e) => {
    e.preventDefault();
    getSentiment();
    setText("");
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>under construction</h1>
        {/* <form onSubmit={handleGetSentiment}>
          <input
            required
            value={text}
            onChange={(e) => setText(e.target.value)}
          />
          <button type="submit">Get Sentiment</button>
        </form> */}
      </div>
    </div>
  );
}
