import Head from "next/head";
import GoEmotions from "../components/GoEmotions";
import Columns from "../components/Columns";

export default function Home() {
  return (
    <>
      <Head>
        <title>.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <GoEmotions />
    </>
  );
}
